version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: training_diary_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all --noauth
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: training_diary_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: